FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish N5.HelloWorld.csproj -c Release -o out -r debian-x64

# Build runtime image
FROM microsoft/dotnet:aspnetcore-sdk
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet"]